import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NextTheme from './_components/Provider/ThemeProvider'
import Navbar from './_components/Navbar'
import BackgroudAnimate from "./_components/BackgroudAnimation"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning className='min-w-full min-h-full'>
      <body className='min-w-full min-h-full' >
        <div>
          <NextTheme >
            <Navbar />
            <BackgroudAnimate />

            <div className='flex w-full h-full mt-20 ' >

              {children}
            </div>
          </NextTheme>
        </div>

      </body>
    </html>
  )
}
