import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}` } >
        <div className='grid grid-cols-10 h-full'>
            <div className="bg-black "></div>
            <div className="bg-zinc-900 col-span-8">
                    {children}  
            </div>
            <div className="bg-black"></div>
        </div>
      </body>
    </html>
  )
}
